default_stages: [pre-commit]
repos:
  - repo: https://github.com/yyang-pplus/config-sh.git
    rev: 5883cd54c082dcae3f34125b9cfcc250b31f79ee
    hooks:
      - id: astyle-c-in
      - id: shfmt

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.1
    hooks:
      - id: clang-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [pre-commit]
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: trailing-whitespace
        stages: [pre-commit]

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
      - id: cmake-lint
