default_stages: [commit]
repos:
  - repo: https://github.com/yyang-pplus/config-sh.git
    rev: 928dadbbd33bc227a4eadd9a2b717f21f273ad1d
    hooks:
      - id: astyle-c
      - id: astyle-cpp
      - id: shfmt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: trailing-whitespace
        stages: [commit]

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
      - id: cmake-lint
