#!/bin/sh

astyle_config="scripts/astyle.rc"

echo "Running Astyle..."
# Current directory is set to the top level of the working tree
which astyle &> /dev/null
if [ $? -eq 0 ] && [ -f $astyle_config ]; then
    astyle --recursive --options=$astyle_config "*.cpp" "*.h"
fi
